theme: jekyll-theme-midnight
title: Introduction to Bioinformatics Class S18
descriptiption: A hands-on introduction to the computer-based analysis of genomic and biomolecular data.
logo: (https://bioboot.github.io/bimm143_S18/assets/img/logo.png)
